

EMPTY_SPIKE = [0, None]

INITIAL_SPIKES_STATE = \
            [[2, 'W'], EMPTY_SPIKE, EMPTY_SPIKE, EMPTY_SPIKE, EMPTY_SPIKE, [5, 'B'],
                    EMPTY_SPIKE, [3, 'B'], EMPTY_SPIKE, EMPTY_SPIKE, EMPTY_SPIKE, [5, 'W'],
             [5, 'B'], EMPTY_SPIKE, EMPTY_SPIKE, EMPTY_SPIKE, [3, 'W'], EMPTY_SPIKE,
                    [5, 'W'], EMPTY_SPIKE, EMPTY_SPIKE, EMPTY_SPIKE, EMPTY_SPIKE, [2, 'B']]

INITIAL_BAR = {'W' : 0, 'B' : 0}

INITIAL_PLAYER_PERSPECTIVE = 'B'

HOME_SIZE = 6

PLAYERS = ['W', 'B']

MIN_DICE_RESULT = 1
MAX_DICE_RESULT = 6

OUT_OF_BAR_SPECIAL_MOVE = (-1)


